--[[ Red Fox -- generated by tools/write_definitions.py

    Three stages on the vanilla "raccoon" skeleton and animation set: kwc_foxkit,
    kwc_foxvixen and kwc_foxdog.

    The two adults SHARE a mesh and differ only in size, which is what vanilla
    does for raccoon, rat and mouse, and what the real animal does too -- there is
    no fox equivalent of antlers. The baby has its own mesh because a juvenile is
    not a scaled-down adult.

    Behaviour is inherited wholesale from the donor species by copying its table,
    so this starts out behaving like a raccoon and differs in what you see and how
    big it is. Sounds, butchering yields and inventory icons are still the
    donor's.

    Regenerate with:
        python3 tools/write_definitions.py --out <mod>/media
]]

require "Definitions/animal/RaccoonDefinitions"

AnimalDefinitions = AnimalDefinitions or {};
AnimalDefinitions.animals = AnimalDefinitions.animals or {};
AnimalDefinitions.stages  = AnimalDefinitions.stages  or {};
AnimalDefinitions.breeds  = AnimalDefinitions.breeds  or {};

local GROUP   = "kwc_fox";
local TEXTURE = "KWC_Fox";

local BABY   = "kwc_foxkit";
local FEMALE = "kwc_foxvixen";
local MALE   = "kwc_foxdog";

local function shallowCopy(t)
    local out = {};
    for k, v in pairs(t) do out[k] = v; end
    return out;
end

local adultSrc = AnimalDefinitions.animals["raccoonboar"];
local babySrc  = AnimalDefinitions.animals["raccoonkit"] or adultSrc;
if not adultSrc then
    print("[" .. GROUP .. "] donor 'raccoonboar' not found; is RaccoonDefinitions loaded?");
    return;
end

-- Sounds hang off the BREED, not the animal -- vanilla does
-- `animals["raccoonboar"].breeds["grey"].sounds = raccoon_sounds`. Building a
-- fresh breed without one therefore makes the animal completely silent, which is
-- exactly what the first version of this file did.
--
-- So the donor's table is inherited wholesale, which gets the right keys and
-- slots for this skeleton for free (raccoon uses walkFront/walkBack, rat uses a
-- single idle_walk plus scuttle sounds), and only the four voice entries are
-- redirected to ours.
local function inheritSounds(donorId, overrides)
    local out = {};
    local src = AnimalDefinitions.animals[donorId];
    local base = nil;
    if src and src.breeds then
        for _, b in pairs(src.breeds) do
            if b.sounds then base = b.sounds; break; end
        end
    end
    if base then
        for k, v in pairs(base) do out[k] = v; end
    else
        print("[" .. GROUP .. "] donor '" .. tostring(donorId) ..
              "' had no sounds; this animal will be silent");
    end
    for key, spec in pairs(overrides) do
        local e = {};
        if out[key] then for kk, vv in pairs(out[key]) do e[kk] = vv; end
        else e.slot = "voice"; end
        for kk, vv in pairs(spec) do e[kk] = vv; end
        out[key] = e;
    end
    return out;
end

-- The intervals matter as much as the clips. See INTERVAL in
-- tools/write_definitions.py for why the donor's 10-20s idle is wrong here.
local adultSounds = inheritSounds("raccoonboar", {
    idle     = { name = "KWC_FoxAdult_Idle",     intervalMin = 300, intervalMax = 900 },
    stressed = { name = "KWC_FoxAdult_Stressed", intervalMin = 45, intervalMax = 110 },
    pain     = { name = "KWC_FoxAdult_Pain" },
    death    = { name = "KWC_FoxAdult_Death" },
});
local babySounds = inheritSounds("raccoonkit", {
    idle     = { name = "KWC_FoxBaby_Idle",     intervalMin = 300, intervalMax = 900 },
    stressed = { name = "KWC_FoxBaby_Stressed", intervalMin = 45, intervalMax = 110 },
    pain     = { name = "KWC_FoxBaby_Pain" },
    death    = { name = "KWC_FoxBaby_Death" },
});

-- Breeds carry the texture and the sounds, so this species needs its own set
-- rather than the donor's. The two adults share a coat; the baby differs only in
-- which voice it uses.
-- Start from the donor's breed rather than an empty table. A vanilla breed carries
-- more than a texture -- rottenTexture, and the inventory icons for alive, dead and
-- skeletal states -- and anything left unset simply has no texture to draw. Ours
-- overrides what it has its own art for and inherits the rest, so a rotting or
-- picked-up critter still renders something instead of nothing.
local function breedFrom(donorId, sounds)
    local base = nil;
    local src = AnimalDefinitions.animals[donorId];
    if src and src.breeds then
        for _, b in pairs(src.breeds) do base = b; break; end
    end
    local out = {};
    if base then for k, v in pairs(base) do out[k] = v; end end
    out.name          = "default";
    out.texture       = TEXTURE;
    out.textureMale   = TEXTURE;
    -- No separate rotting art yet, so point it at our own coat. Left unset it
    -- would fall through to the donor's, and a rotting squirrel would turn rat.
    out.rottenTexture = TEXTURE;
    out.sounds        = sounds;
    return out;
end

AnimalDefinitions.breeds[GROUP] = { breeds = {
    default = breedFrom("raccoonboar", adultSounds),
} };

local babyBreeds = { default = breedFrom("raccoonkit", babySounds) };

-- This species' OWN stages. Pointing at the donor's would grow the baby into a
-- raccoon.
AnimalDefinitions.stages[GROUP] = { stages = {
    [BABY]   = { ageToGrow = 75, nextStage = FEMALE, nextStageMale = MALE },
    [FEMALE] = { ageToGrow = 75 },
    [MALE]   = { ageToGrow = 75 },
} };

-- Stage 1 aggression (see tools/write_definitions.py). Data only: whether this
-- animal can fight, at what range and how often. No targeting lives here, and
-- nothing scans for a victim -- that is stage 2 of STATUS 7g.
--
-- The donor sets NO attack field at all, so without this the animal simply
-- cannot fight. attackTimer is a cooldown and LOWER IS FASTER; vanilla runs
-- mouse 1500, sow 2000, hen 3500, ewe 6000, cow 8200. attackDist 0 is vanilla's
-- way of saying harmless (mouse, rat, chick, turkeypoult).
--
-- Babies never fight, matching chick/turkeypoult/mousepups.
local ADULT_AGGRO = { dist = 1, timer = 3000,
                      back = true, stressed = true };
local BABY_AGGRO  = { dist = 0, timer = 4000, back = false, stressed = false };

local function define(id, src, model, minSize, maxSize, minWeight, maxWeight, male, breeds, aggro)
    local a = shallowCopy(src);
    a.bodyModel = model;
    a.breeds    = breeds or AnimalDefinitions.breeds[GROUP].breeds;
    a.stages    = AnimalDefinitions.stages[GROUP].stages;
    a.group     = GROUP;
    a.minSize   = minSize;
    a.maxSize   = maxSize;
    a.minWeight = minWeight;
    a.maxWeight = maxWeight;
    a.male      = male or false;
    a.wild      = true;
    if aggro then
        a.attackDist       = aggro.dist;
        a.attackTimer      = aggro.timer;
        a.attackBack       = aggro.back;
        a.attackIfStressed = aggro.stressed;
    end
    -- Designation zones silently domesticate-and-de-wild animals every ~2000
    -- ticks, nulling their migration group. A wild critter must never be
    -- eligible.
    a.canBeDomesticated = false;
    AnimalDefinitions.animals[id] = a;
    return a;
end

define(BABY,   babySrc,  "KWC_FoxKit", 0.897, 1.523, 0.5, 2.5, false, babyBreeds, BABY_AGGRO);
define(FEMALE, adultSrc, "KWC_Fox", 1.79, 2.06, 4.0, 6.0, false, nil, ADULT_AGGRO);
define(MALE,   adultSrc, "KWC_Fox", 1.97, 2.282, 5.0, 7.5, true,  nil);

-- Breeding pairs, and what a newborn is. Set AFTER all three exist so the ids
-- resolve.
AnimalDefinitions.animals[FEMALE].mate     = MALE;
AnimalDefinitions.animals[MALE].mate       = FEMALE;
AnimalDefinitions.animals[FEMALE].babyType = BABY;
AnimalDefinitions.animals[MALE].babyType   = BABY;
AnimalDefinitions.animals[BABY].mate       = nil;
AnimalDefinitions.animals[BABY].babyType   = nil;
